#!/bin/bash


myfile=$(mktemp)
cat "$1" | egrep "#.*if|#else|$2" > $myfile
indent_num=0
indent="  "
while IFS="" read -r line
do
    if [[ "$line" =~ \#.*if ]]; then
	if [[ "$line" =~ \#.*endif ]]; then
	    let "indent_num--"
	    indent=$(echo "$indent" | cut -c3-${#indent})
	    echo "| $indent$line"
	elif [[ "$line" =~ \#.*elif ]]; then
	    echo "$indent$line"
	else
	    echo "| $indent$line"
	    let "indent_num++"
	    indent="$indent| "
	fi
    elif [[ "$line" =~ \#else ]]; then
	echo "$indent$line"
    else
	echo "@ $indent$line"
    fi
    
    
    
done < $myfile
