#!/bin/bash

if [[ -z $1 ]]; then
    echo "must provide name of dir to save to within saves"
    exit
fi

mkdir /home/dale/wkelliher/mybranch/saves/$1

for x in $(svn st | grep "^\(M\|?\)" | grep -v "default" | sed 's/.[[:space:]]*\(.*\)/\1/'); do
    cp $x "/home/dale/wkelliher/mybranch/saves/$1/"
done

