#!/bin/bash

if [ "$1" == "," ]; then
    cd "$Q"
else
    cd ${1:-.}
fi

clear
ls --ignore="*.pyc" -a

if [ "$1" != "," ]; then
    export Q="$(pwd)"
    #echo "$(pwd)" > /home/dale/bin/.last_d
fi
   
