#!/bin/bash

if [ -n "$1" ]; then
    MYTOOLS="$1"
fi

cd $MYTOOLS/linux64-comp
../dobuild intex
echo "cp intex $MYOSTOOLS/"
cp intex $MYOSTOOLS/

cd ../linux64-ide
../dobuild ints_sharedobj.so
echo "cp ints_sharedobj.so $MYOSTOOLS/"
cp ints_sharedobj.so $MYOSTOOLS/


# NOTE: if you get a link error then you have to run `$MYTOOLS/bin/scripts/cvlink update`
